Repository jellyfin/jellyfin-plugin-opensubtitles, pull requests merged in 2021-11, with the labels that each got.

#68 10.8 support
  .github/workflows/build-dotnet.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/test-dotnet.yml
  Jellyfin.Plugin.OpenSubtitles/Jellyfin.Plugin.OpenSubtitles.csproj
  OpenSubtitlesHandler/OpenSubtitlesHandler.csproj
Labels: chore

#75 Search improvements vol. 2 + minor fixes
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitleDownloader.cs
  OpenSubtitlesHandler/Models/ApiResponse.cs
  OpenSubtitlesHandler/Models/Responses/SubtitleDownloadInfo.cs
  OpenSubtitlesHandler/OpenSubtitles.cs
Labels: feature

#78 bump targetAbi to 10.8
  .github/workflows/update-release-draft.yml
  build.yaml
Labels: chore

#81 Fix build.yaml, fix new build errors
  .github/workflows/build-dotnet.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/test-dotnet.yml
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitleDownloader.cs
  build.yaml
  jellyfin.ruleset
Labels: chore

#83 Better download limit handling
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitleDownloader.cs
  README.md
Labels: feature

#85 Move OpenSubtitlesHandler project to folder
  Jellyfin.Plugin.OpenSubtitles.sln
  Jellyfin.Plugin.OpenSubtitles/API/OpenSubtitlesController.cs
  Jellyfin.Plugin.OpenSubtitles/Jellyfin.Plugin.OpenSubtitles.csproj
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitleDownloader.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/ApiResponse.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/ErrorResponse.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/HttpResponse.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/JWTPayload.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/LoginInfoInput.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/Responses/Attributes.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/Responses/EncapsulatedLanguageList.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/Responses/EncapsulatedUserInfo.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/Responses/FeatureDetails.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/Responses/LanguageInfo.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/Responses/LoginInfo.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/Responses/ResponseData.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/Responses/SearchResult.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/Responses/SubFile.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/Responses/SubtitleDownloadInfo.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/Responses/Uploader.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/Models/Responses/UserInfo.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/OpenSubtitles.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/OpenSubtitlesRequestHelper.cs
  Jellyfin.Plugin.OpenSubtitles/OpenSubtitlesHandler/RequestHandler.cs
  build.yaml
Labels: bug
